site_name: My Aviation Project
theme:
  name: material

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"

markdown_extensions:
  - footnotes
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - bibtex:
      bib_file: "https://api.zotero.org/groups/5782724/collections/G847TDER/items?format=bibtex"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
