site_name: My Aviation Project
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.expand
    - toc.integrate

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"
  - API Documentation:
      - Aviation Project: api/index.md
      - Aviation Module: api/aviation.md

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocstrings
  - bibtex:
      bib_file: "https://api.zotero.org/groups/5782724/collections/G847TDER/items?format=bibtex"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
