site_name: My Aviation Project
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - bibtex:
      bib_file: "https://api.zotero.org/groups/5782724/collections/G847TDER/items?format=bibtex"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
