site_name: My Aviation Project
theme:
    name: material

nav:
  - Home: 'index.md'
  - Aviation Model: 'aviation.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js