[project]
name = "aviation"
version = "0.1.0"
description = "Global model for Aviation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
docs = [
    "mkdocs-material>=9.6.15",
]
