name: Check

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        with:
          enable-cache: true
        uses: astral-sh/setup-uv@v6
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: install depencencies
        run: uv sync
      - name: lint with ruff
        run: uv run ruff check
      - name: format with ruff
        run: uv run ruff format
      - name: check with precommit
        run: uv run pre-commit run --all-files
